### ISSUE TITLE
Failed to respond

### ISSUE THREAD

**Issue by random-guy9182** [Hary309/Flow.Launcher.Plugin.FlowTrumpet#3]
[2024-11-28.txt](https://github.com/user-attachments/files/17948436/2024-11-28.txt)

It was working for a bit but now it doesnt work at all. The plugin will be disabled on startup and will show me this error when I enable it.

Flow Launcher version: 1.19.4
OS Version: 26100.2314
IntPtr Length: 8
x64: True

Python Path: C:\Users\[my user]\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 11/28/2024 21:04:55
Exception:
FlowTrumpet Exception: 
Websites: https://github.com/Hary309/Flow.Launcher.Plugin.FlowTrumpet
Author: Hary309
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Flow.Launcher.Plugin.FlowTrumpet.Main.Query(Query query)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Hary309** [comment]
I am not sure, I am using this from the released and I had no issues.

**Comment by Hary309** [comment]
What plugins do you have installed?

**Comment by random-guy9182** [comment]
I just tried installing flowtrumpet again and it seems to be working fine now. Though last time it was working it would randomly disable itself so I'm not entirely sure it's fixed yet. As for the plugins, I may have installed a few more since the first post but I'll list the ones currently installed.

AnyVideo Downloader
Browser Bookmarks
Calculator
Explorer
Favourites
Flowtrumpet
Playnite
Plugins Manager
Process Killer
RemoveUSB
Shell
System Commands
Web Searches
Windows Settings
